name: Python Checks
on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    strategy:
      matrix:
        python-versions: [3.8,3.9]

    services:
      centos:
        image: calebjstewart/pwncat-testing:centos
      ubuntu:
        image: calebjstewart/pwncat-testing:ubuntu

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pwncat
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
          python setup.py install --user
#       - name: Lint with flake8
#         run: |
#           flake8
      - name: Test with pytest
        env:
          CENTOS_HOST: "centos"
          CENTOS_BIND_PORT: "4444"
          UBUNTU_HOST: "ubuntu"
          UBUNTU_BIND_PORT: "4444"
        run: |
          pytest
